/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d4dbdf',
        'surface-container-low': '#f0f4f7',
        'surface-container': '#eaeff2',
        'surface-container-high': '#e3e9ed',
        'surface-container-highest': '#dce4e8',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#2c3437',
        'on-surface-variant': '#596064',
        'on-background': '#2c3437',
        'primary': 'var(--c-primary, #006592)',
        'primary-container': 'var(--c-primary-container, #34b5fa)',
        'primary-light': 'var(--c-primary-light, #17a8ec)',
        'on-primary': '#f5f9ff',
        'on-primary-container': '#003047',
        'secondary': 'var(--c-secondary, #50616f)',
        'secondary-container': '#d3e5f5',
        'on-secondary': '#f5f9ff',
        'tertiary': 'var(--c-tertiary, #585c85)',
        'outline': '#747c80',
        'outline-variant': '#acb3b7',
        'error': '#a83836',
        'error-container': '#fa746f',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
      },
      fontFamily: {
        'manrope': ['Manrope', 'sans-serif'],
        'headline': ['Manrope', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
      letterSpacing: {
        'tight-headline': '-0.025em',
      },
      boxShadow: {
        'tonal': '0 1px 3px 0 rgba(0,101,146,0.04), 0 1px 2px -1px rgba(0,101,146,0.04)',
        'tonal-md': '0 4px 12px -2px rgba(0,101,146,0.06), 0 2px 6px -2px rgba(0,101,146,0.04)',
        'tonal-lg': '0 8px 24px -4px rgba(0,101,146,0.08), 0 4px 8px -4px rgba(0,101,146,0.04)',
        'editorial': '0px 20px 40px rgba(0, 101, 146, 0.06)',
      },
      borderRadius: {
        'DEFAULT': '1rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
        '4xl': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
      },
    },
  },
  plugins: [],
};
